config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  namespace :api, format: 'json' do
    resources :topics, only: %i(create) do
      scope module: :topics do
        resources :comments, only: %i(create)
      end
    end
    resources :categories, only: %i(index)
    resources :icon, only: :index
    post 'reactions/:type/' => 'reactions#create'
    post 'reactions/:type/:reactionable_id' => 'reactions#destroy'
  end

  resources :topics do
    get :reaction_count_map
    collection do
      get :complete
      get :search
    end
    scope module: :topics do
      get 'comments/:no/anchor' => 'comments#anchor', as: 'anchor'
    end
  end
  resources :categories, only: :show, path: 'category'
  get 'tags/:name' => 'tags#index', as: :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Jpmobile::ViewSelector
  before_action :set_identity_cookie

  protect_from_forgery with: :exception

  private

  def pc?
    !request.smart_phone?
  end

  def set_identity_cookie
    return if cookies['_cadr'].present?
    hash_ip = Digest::MD5.hexdigest(request.remote_ip)
    cookies.permanent['_cadr'] = {
      value: Time.zone.now.to_s(:yyyymmdd) + hash_ip
    }
  end
end

app/controllers/topics/application_controller.rb
class Topics::ApplicationController < ApplicationController
  layout 'topic'
end

app/helpers/application_helper.rb
module ApplicationHelper
  def category?
    controller_path == "categories"
  end
end

app/views/application/common/_footer.html.slim
.u-bg-brown
  .l__footer
    footer.c-flex
      .footer-col
        p = t('site_name')
      .footer-col
        .footer__pages-title
          | カテゴリー一覧
        ul.footer__pages
          - Category.all.each do |category|
            li = link_to category.name, category
      .footer-col
        .footer__pages-title
          = t('site_name')
        ul.footer__pages
          li
            | サービスについて
          li
            | 利用規約
          li
            | プライバシーポリシー

app/views/application/common/_header.html.slim
.u-bg-pink
  .l__header
    header.c-flex.c-flex__jc-sb.c-flex__ai-c.u-h-100p
      .c-flex.c-flex__jc-sb.c-flex__ai-c.c-header__left-w
        - if params[:controller] == 'top'
          h1.text--s-xx-lg.u-font--nunito = link_to t('site_name'), root_path, class: "c-link--c-w"
        - else
          .text--s-xx-lg.u-font--nunito = link_to t('site_name'), root_path, class: "c-link--c-w"
        form
          input class="c-search__form" placeholder="スレ検索"
          button
            i.fa.fa-search.c-search__icon

app/views/application/common/_side_menu.html.slim
ul.c-side-list
  li = link_to "マイページ", home_path, class: "c-side-my-page-list__item"
  li = link_to "プロフィールを変更する", edit_home_path, class: "c-side-my-page-list__item"
  li = link_to "メールアドレスを変更する", email_home_path, class: "c-side-my-page-list__item"
  li = link_to "パスワードを変更する", password_home_path, class: "c-side-my-page-list__item"

app/views/application/common/_side_menu_left.html.slim
.l-side__container
  nav.c-left-navi
    ul
      li class=("is-active" if request.url == root_url)
        = link_to "ホーム", root_path
      - @categories.each do |category|
        li class=("is-active" if (category.id == params[:id].to_i && category?))
          = link_to category.name, category_path(category)

app/views/application/common/_side_profile.html.slim
.c_container
  .c-frame.c-border
    .c-grid__thumb.text--c
      = image_tag('woman-face.png')
    p.text--c = @member.name
    - unless @member.unselected?
      p.text--c = t("enums.user.sex.#{@member.sex}")
    - if current_user == @member
      = link_to "プロフィール編集", edit_home_path,
        class: "c-btn c-btn--w-100p c-btn--gray text--c text--s-md"

app/views/application/common/_tag_ranking.html.slim
.c_container
  h3.c-side-title
    | 人気タグ
  p.c-side-description
    | よく使われているキーワードです
  ul.c-tags
    - tags.each do |tag|
      li.c-tag
        i.fa.fa-tag.c-icon-pink
        span.c-tag--name = link_to tag.name, tags_path(tag.name)

app/views/application/common/_topics.html.slim
= link_to topic, class: "c-link__block" do
  li.c-list__item.c-flex
    .c-grid__thumb.c-border__img-r-10
      - if topic.image?
        = image_tag topic.image.url(:thumbnail)
      - elsif topic.thumbnails_first
        = image_tag topic.thumbnails_first
      - else
        = image_tag('no_image.png')
    .c-grid__content
      .c-grid__title
        = topic.title
      .c-grid__info
        i.fa.fa-commenting.c-icon-gray
        .c-icon__value
          = topic.comments.count
          | コメント