config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  namespace :api, format: 'json' do
    resources :topics, only: %i(create) do
      scope module: :topics do
        resources :comments, only: %i(create)
      end
    end
    resources :categories, only: %i(index)
    resources :icon, only: :index
    post 'reactions/:type/' => 'reactions#create'
    post 'reactions/:type/:reactionable_id' => 'reactions#destroy'
  end

  resources :topics do
    get :reaction_count_map
    collection do
      get :complete
      get :search
    end
    scope module: :topics do
      get 'comments/:no/anchor' => 'comments#anchor', as: 'anchor'
    end
  end
  resources :categories, only: :show, path: 'category'
  get 'tags/:name' => 'tags#index', as: :tags
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  acts_as_taggable
  has_attached_file :image,
    styles: { normal: '500x500>',
              thumbnail: '140x140>' }

  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy, as: :reactionable
  has_many :comment_reactions, through: :comments, source: :reactions
  has_many :icons, through: :reactions

  belongs_to :category

  before_create :process_body

  after_create :add_tags

  validates :title, presence: true
  validates :body, presence: true
  validates :name, presence: true
  validates_attachment :image,
    content_type: { content_type: ['image/jpg',
                                   'image/jpeg',
                                   'image/png',
                                   'image/gif',
                                   'image/bmp'] },
    less_than: 20.megabytes

  def thumbnails_first
    thumbnails_urls.first
  end

  def add_tags
    tag_list = ActsAsTaggableOn::Tag.all.pluck(:name)
    tag_list.each do |tag|
      if title.include?(tag)
        self.tag_list << tag
      end
    end

    tag_list.each do |tag|
      if body.include?(tag)
        self.tag_list << tag
      end
    end
  end

  private

  def thumbnails_urls
    URI.extract(body, Constants::URL_SCHEMES).select do |url|
      url.match(/\.(jpg|jpeg|png|gif|bmp)$/)
    end
  end

  def process_body
    self.body = ContentsView.new(body).processing_display
  end
end

app/controllers/api/topics/comments_controller.rb
class Api::Topics::CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      render json: @comment, status: 200
    else
      render json: { errors: @comment.errors,
                     error_messages: @comment.errors.full_messages },
             status: 422
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body,
                                    :name,
                                    :image,
                                    :topic_id)
  end
end

app/controllers/api/topics_controller.rb
class Api::TopicsController < ApplicationController
  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      render json: @topic, status: 200
    else
      render json: { errors: @topic.errors,
                     error_messages: @topic.errors.full_messages },
             status: 422
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title,
                                  :body,
                                  :category_id,
                                  :name,
                                  :image)
  end
end

app/controllers/topics/application_controller.rb
class Topics::ApplicationController < ApplicationController
  layout 'topic'
end

app/controllers/topics/comments_controller.rb
class Topics::CommentsController < Topics::ApplicationController
  def anchor
    topic = Topic.find(params[:topic_id])
    no = params[:no].to_i
    anchor = no == 1 ? topic : topic.comments[no - 2]
    text = render_to_string partial: 'anchor',
                            locals: { no: no,
                                      anchor: anchor }
    render plain: text, status: 200
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include Cookie
  before_action :set_category, only: :new
  before_action :set_tag_ranking, only: :show
  before_action :set_topic, only: :show

  def new
    if pc?
      render layout: 'one_column'
    end
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to complete_topics_url(id: @topic)
    else
      render :new
    end
  end

  def complete
    if pc?
      render layout: 'one_column'
    end
  end

  def search
    @tag_ranking = ActsAsTaggableOn::Tag.most_used
  end

  def show
    category = @topic.category
    @topics = category.topics.
              where.not(id: @topic.id).
              order(id: :desc).
              limit(3)
    date = Analysis.last.date
    @rankings = Analysis.topic_ranking(date).limit(5).map(&:analysisable)
    render layout: 'topic'
  end

  def reaction_count_map
    @topic = Topic.find(params[:topic_id])
    map = { topic: {}, comment: {} }
    map[:topic] = @topic.icons.group_by(&:id)
    @topic.comments.includes(:icons).each do |comment|
      map[:comment][comment.id] = comment.icons.group_by(&:id)
    end

    map[:topic][:user_reactioned_ids] = @topic.reactions.where(user_cookie_value: identity_id).pluck(:icon_id)
    comment_ids = @topic.comments.pluck(:id)
    comment_ids.each { |comment_id| map[:comment][comment_id][:user_reactioned_ids] = [] }

    ids = @topic.comment_reactions.ids
    icon_ids = @topic.comment_reactions.pluck(:icon_id).uniq
    map_ids = @topic.comment_reactions.where(id: ids,
                                             icon_id: icon_ids,
                                             user_cookie_value: identity_id).
                                             pluck(:reactionable_id, :icon_id)

    map_ids.each do |comment_id, icon_id|
      map[:comment][comment_id][:user_reactioned_ids] << icon_id
    end

    map[:topic][:order] = @topic.reactions.pluck(:icon_id).uniq
    map_ids = @topic.comment_reactions.pluck(:reactionable_id, :icon_id).uniq
    comment_ids = @topic.comments.ids
    comment_ids.each do |comment_id|
      map[:comment][comment_id][:order] = []
    end
    map_ids.each do |comment_id, icon_id|
      map[:comment][comment_id][:order] << icon_id
    end
    render json: map, status: 200
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  end

  def set_tag_ranking
    @tag_ranking = ActsAsTaggableOn::Tag.most_used
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title,
                                  :body,
                                  :category_id,
                                  :name,
                                  :image)
  end
end

app/views/topics/_comments.html.slim
- index = comment_counter + 2
.c-container--sm
  .c-flex
    div
      = index
      |:
    .c-margin-l-10
      = comment.name
    .p-topic-date
      = comment.created_at.to_s(:YmdnHM)

.c-container.p-topic-font
  .c-container.text--b
    = comment.body.html_safe
  - if comment.image?
    .c-container
      .p-topic__image
        = image_tag comment.image.url(:normal)
  reaction-counter reactionable_id=comment.id type="#{comment.class.name}"
  .p-topic-icon.text--s-x-lg
    reaction reply_id="#{index}" v-on:reply="reply" emoji_path=image_path('emoji.png') reactionable_id="#{comment.id}" type="#{comment.class.name}" ref="reaction"

app/views/topics/_comments_smart_phone.html.slim
- index = comment_counter + 2
.c-container--sm
  .c-flex
    div
      = index
      |:
    div.c-margin-l-5.text__c--green.text--b
      = comment.name
    div.c-margin-l-5.text__c--d-gray
      = comment.created_at.to_s(:YmdnHM)

.c-container.p-topic-font
  .c-container.text--b
    = comment.body.html_safe
  - if comment.image?
    .c-container
      .p-topic__image
        = image_tag comment.image.url(:normal)
  reaction-counter reactionable_id=comment.id type="#{comment.class.name}"
  .p-topic-icon.text--s-x-lg
    reaction reply_id="#{index}" v-on:reply="reply" emoji_path=image_path('emoji.png') reactionable_id="#{comment.id}" type="#{comment.class.name}" ref="reaction"

app/views/topics/_image.html.slim
.c-grid__quotation-image
  = image_tag(url)
  = link_to "出典：#{host_name}", url, target: '_blank'

app/views/topics/_link_thumbnail_description.html.slim
- attributes = { class: "c-grid__quotation--link", target: '_blank' }
- rel = nofollow ? { rel: 'nofollow' } : {}

= link_to site.url.to_s, attributes.merge(rel) do
  .c-grid__quotation.text--s-md.p-topic__quotation__border.c-border-r-5
    .c-grid__quotation--main
      = image_tag(url)
    .c-grid__quotation--side
      .c-grid__quotation--side-title.text--b
        = site.title
      .c-grid__quotation--side-description.text--n
        = site.description
      .c-grid__quotation--side-url
        = site.url.host

app/views/topics/complete.html.slim
- title = request.referrer.include?("new") ? "トピック" : "コメント"
- opts = { noindex: true, nofollow: true }
- content_for :meta_tags do
  = display_meta_tags(default_meta_tags(opts))
.l__topic__form.c-border-2
  .c-container
    h1.c-heading--title.text--s-lg
     | 投稿完了
  p
    = "#{title}"
    | の作成ができました。
    br
    = "#{title}"
    | をご覧になる場合は、
    = link_to 'こちら', topic_path(params[:id])
    | になります。
    br
    | 投稿していただき、ありがとうございます。

app/views/topics/new.html.slim
- content_for :meta_tags do
  = display_meta_tags(default_meta_tags)
- content_for :javascript do
  = javascript_pack_tag "topic"

.l__topic__form.c-border-2
  .c-container
    h1.c-heading--title.text--s-lg
     | トピック投稿
  .c-container
    #topic-form-vue
      form-error :count="topic.errors.count" :messages="topic.errors.messages"
      .c-flex
        .c-grid__thumb--form.c-container
          div v-if="!topic.image"
            = image_tag('no_image.png')
          template v-else=""
            img :src="topic.image"
          file-upload v-model="topic.image"
        .c-form
          .c-container
            select class="c-form__select" v-model="topic.category_id"
              option v-for="category in categories" :value="category.id"
                = "{{category.name}}"
          .c-container :class="isError('name')"
            input type="text" v-model="topic.name" class="c-form__input c-form-w-100" placeholder="名前を入力してください"
          .c-container :class="isError('title')"
            input type="text" v-model="topic.title" class="c-form__input c-form-w-100" placeholder="タイトルを入力してください"
          .c-container :class="isError('body')"
            textarea v-model="topic.body" class="c-form__text_area c-form--h-200 c-form-w-100" placeholder="本文を入力してください"
            .c-flex.c-flex__jc-sb
              icon v-on:show="openModal"
              div
                input type="submit" class="c-btn c-btn--pink c-btn--md" data-disable-with="処理中..." @click="submit"
      modal v-show="modalActive" v-on:close="closeModal" v-on:url="addUrl"

app/views/topics/new_smart_phone.html.slim
- content_for :meta_tags do
  = display_meta_tags(default_meta_tags)
- content_for :javascript do
  = javascript_pack_tag 'sp/topic'

.c-padding-10
  .c-container--sm
    h1.text--s-md.text--b
      | トピックを投稿する
  .c-container--sm
    #topic-form-vue
      form-error :count="topic.errors.count" :messages="topic.errors.messages"
      .c-flex
        .c-grid__thumb.c-container--sm
          div v-if="!topic.image"
            = image_tag('no_image.png')
          template v-else=""
            img :src="topic.image"
        .c-form.c-margin-l-10
          .c-container--sm
            select class="c-form__select text--s-slg" v-model="topic.category_id"
              option v-for="category in categories" :value="category.id"
                = "{{category.name}}"
          .c-container--sm :class="isError('name')"
            input type="text" v-model="topic.name" class="c-form__input u-w-100p text--s-slg" placeholder="名前を入力してください"
      .c-form
        .c-container--sm :class="isError('title')"
          input type="text" v-model="topic.title" class="c-form__input u-w-100p text--s-slg" placeholder="タイトルを入力してください"
        .c-container--sm :class="isError('body')"
          textarea v-model="topic.body" class="c-form__text_area c-form--h-200 u-w-100p text--s-slg" placeholder="本文を入力してください"
          .c-flex
            file-upload v-model="topic.image"
            icon v-on:show="openModal"
        input type="submit" class="c-btn c-btn--pink u-w-100p text--s-slg" data-disable-with="処理中..." @click="submit"
      modal v-show="modalActive" v-on:close="closeModal" v-on:url="addUrl"

app/views/topics/search_smart_phone.html.slim
- content_for :meta_tags do
  = display_meta_tags(default_meta_tags)
- breadcrumb :search_topics, @topic
- content_for :breadcrumbs do
  = render "application/s/breadcrumbs"
h1.c-heading.text--s-x-lg.text--b.c-border--bottom-3.c-border__c-p.c-container
  | 人気のキーワード
ul.c-tags.c-padding-l-10.c-padding-r-10
  - @tag_ranking.each do |tag|
    li.c-tag
      i.fa.fa-tag.c-icon-pink
      span.c-tag--name = link_to tag.name, tags_path(tag.name)

app/views/topics/show.html.slim
- content_for :meta_tags do
  = display_meta_tags(topic_meta_tags(@topic))
- content_for :tag_ranking do
  = render "application/common/tag_ranking", tags: @tag_ranking
- content_for :javascript do
  = javascript_pack_tag "comment"
- breadcrumb :thread, @topic

#vue
  .c-container
    .c-flex.p-topic--title__border
      .c-flex--column
        - if @topic.image?
          = image_tag(@topic.image.url(:thumbnail), class: "p-topic__thumbnail c-border-r-10")
        - elsif @topic.thumbnails_first
          = image_tag(@topic.thumbnails_first, class: "p-topic__thumbnail c-border-r-10")
        -else
          = image_tag('no_image.png', class: "p-topic__thumbnail c-border-r-10")
        .p-topic--comment.text--s-sm
          span.text--s-lg.text__c--pink.text--b
            = @topic.comments.count
          | コメ
      .c-flex--column.c-flex__jc-sb
        .c-flex.c-flex__jc-sb
          .text--s-sm.text__c--d-gray
            - if @topic.comments.present?
              = @topic.comments.last.updated_at.to_s(:YmdnHM)
            - else
              = @topic.updated_at.to_s(:YmdnHM)
        h1.p-topic--title.text--s-xx-lg.text--b.c-container--sm
          = @topic.title
        .c-flex.c-flex__jc-sb
          .c-category--item
            .text--b.c-margin-reset.text--c
              = @topic.category.name

  - if @topic.image?
    .c-container
      .p-topic__image
        = image_tag(@topic.image.url(:normal))

  .c-container--sm
    .c-flex
      div
        | 1:
      .c-margin-l-10
        = @topic.name
      .p-topic-date
        = @topic.created_at.to_s(:YmdnHM)

  .c-container.p-topic-font
    .c-container.text--b
      = @topic.body.html_safe

  reaction-counter reactionable_id=@topic.id type="#{@topic.class.name}"
  .p-topic-icon.text--s-x-lg
    reaction reply_id="1" v-on:reply="reply" emoji_path=image_path('emoji.png') reactionable_id="#{@topic.id}" type="#{@topic.class.name}" ref="reaction"

  = render partial: "comments", collection: @topic.comments.includes(:icons), as: :comment

  - if @topic.tags.present?
    .c-container--sm.c-heading--section.text--s-lg.text--b
      | 関連キーワード
    ul.c-tags
      - @topic.tags.each do |tag|
        li.c-tag
          i.fa.fa-tag.c-icon-pink
          span.c-tag--name = link_to tag.name, tags_path(tag.name)

  .c-container--sm.c-heading--section.text--s-lg.text--b
    | コメントする
  .c-container
    form-error :count="comment.errors.count" :messages="comment.errors.messages"
    .c-flex--column.c-container--sm
      label
        | 名前
      input type="text" v-model="comment.name" class="c-form__input c-form-w-50p" placeholder="名前を入力してください"
    .c-flex--column.c-container--sm
      label
        | 本文
      textarea v-model="comment.body" class="c-form__text_area c-form--h-200 c-form-w-100" placeholder="本文を入力してください" data-text-area=true
    .c-container--sm
      div v-show="comment.image"
        .c-container--sm
          .p-comment-thumbnail.c-border.c-border-r-4
            img :src="comment.image"
            i class="fa fa-close c-icon-white p-comment__img--close" @click="imageDelete"
    icon v-model="comment.image" v-on:open="openModal"
    modal v-show="modalActive" v-on:close="closeModal" v-on:url="addUrl"
    reaction-error v-show="errorReaction.visiable"
  .text--c.c-container
    input type="submit" class="c-btn c-btn--pink c-btn--w-275 c-btn--h-large" data-disable-with="処理中..." @click="submit"

  .c-container--sm.c-heading--section.text--s-lg.text--b
    | 人気のトピック
  ul.c-list
    = render partial: "application/common/topics", collection: @rankings, as: :topic

app/views/topics/show_smart_phone.html.slim
- content_for :meta_tags do
  = display_meta_tags(topic_meta_tags(@topic))
- breadcrumb :thread, @topic
- content_for :javascript do
  = javascript_pack_tag 'sp/comment'
- content_for :breadcrumbs do
  = render "application/s/breadcrumbs"

#vue
  - if @topic.image?
    .c-container--sm.p-topic__image
      = image_tag(@topic.image.url(:normal))
  - elsif @topic.thumbnails_first
    .c-container--sm.p-topic__image
      = image_tag(@topic.thumbnails_first)
  .c-container--sm
    h1.c-heading.text--s-x-lg.text--b.c-border--bottom-3.c-border__c-p
      = @topic.title
  .p-topic-container
    .c-flex.c-flex__jc-sb.c-container--sm
      div
        - if @topic.comments.present?
          = @topic.comments.last.updated_at.to_s(:YmdnHM)
        - else
          = @topic.updated_at.to_s(:YmdnHM)
      div
        = @topic.comments.count
        | コメント

    .c-container--sm
      .c-flex
        div
          | 1:
        div.c-margin-l-5.text__c--green.text--b
          = @topic.name
        div.c-margin-l-5.text__c--d-gray
          = @topic.created_at.to_s(:YmdnHM)

    .c-container.p-topic-font
      .c-container.text--b
        = @topic.body.html_safe

    reaction-counter reactionable_id=@topic.id type="#{@topic.class.name}"
    .p-topic-icon.text--s-x-lg
      reaction reply_id="1" v-on:reply="reply" emoji_path=image_path('emoji.png') reactionable_id="#{@topic.id}" type="#{@topic.class.name}" ref="reaction"

    = render partial: "comments", collection: @topic.comments.includes(:icons), as: :comment
    - if @topic.tags.present?
      .c-container--sm.c-padding-l-10.text--s-lg.text--b.c-border--left-3.c-border__c-p
        | 関連タグ
      ul.c-tags
        - @topic.tags.each do |tag|
          li.c-tag
            i.fa.fa-tag.c-icon-pink
            span.c-tag--name = link_to tag.name, tags_path(tag.name)

    .c-container--sm.c-padding-l-10.text--s-lg.text--b.c-border--left-3.c-border__c-p
      | コメントを投稿する
    form-error :count="comment.errors.count" :messages="comment.errors.messages"
    .c-container--sm
      .c-flex--column.c-container--sm
        label
          | 名前
        input type="text" v-model="comment.name" class="c-form__input text--s-slg u-w-100p" placeholder="名前を入力してください"
      .c-flex--column.c-container--sm
        label
          | 本文
        textarea v-model="comment.body" class="c-form__text_area text--s-slg c-form--h-200 u-w-100p" placeholder="本文を入力してください" data-text-area=true
      .c-flex
        file-upload v-model="comment.image"
        icon v-on:show="openModal"
    .c-container--sm
      div v-show="comment.image"
        .c-container--sm
          .c-grid__thumb.c-border-r-4
            img :src="comment.image"
            i class="fa fa-close c-icon-white p-comment__img--close" @click="imageDelete"
    .text--c.c-container
      input type="submit" class="c-btn c-btn--pink u-w-100p text--s-slg" data-disable-with="処理中..." @click="submit"
    .text--s-lg.text--b.c-border--bottom-1.c-border__c-p
      | 人気トピック
    .c-container--sm
      = render partial: "application/s/common/topics", collection: @rankings, as: :topic, locals: { ranking: true }
    .text--s-lg.text--b.c-border--bottom-1.c-border__c-p
      | 関連トピック
    .c-container--sm
      = render partial: "application/s/common/topics", collection: @topics, as: :topic
    modal v-show="modalActive" v-on:close="closeModal" v-on:url="addUrl"
    reaction-error v-show="errorReaction.visiable"