config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  namespace :api, format: 'json' do
    resources :topics, only: %i(create) do
      scope module: :topics do
        resources :comments, only: %i(create)
      end
    end
    resources :categories, only: %i(index)
    resources :icon, only: :index
    post 'reactions/:type/' => 'reactions#create'
    post 'reactions/:type/:reactionable_id' => 'reactions#destroy'
  end

  resources :topics do
    get :reaction_count_map
    collection do
      get :complete
      get :search
    end
    scope module: :topics do
      get 'comments/:no/anchor' => 'comments#anchor', as: 'anchor'
    end
  end
  resources :categories, only: :show, path: 'category'
  get 'tags/:name' => 'tags#index', as: :tags
end

app/views/application/s/common/_footer.html.slim
footer.l__footer.u-bg-pink
  ul.c-flex.c-margin-reset.c-flex__wrap.c-border--top-1.c-border--left-1.c-border--bottom-1.c-border__c-l-p
    - Category.all.each do |category|
      - case category.id
      - when 1
        = link_to category, class: "u-w-50p c-footer__list" do
          i.fa.fa-cutlery.text--s-lg.text__c--white.c-flex.c-padding-l-10.c-fotter__list--name
            li.c-padding-l-10.text--b.text__c--white.text--s-slg  = category.name
      - when 2
        = link_to category, class: "u-w-50p c-footer__list" do
          i.fa.fa-heart.text--s-lg.text__c--white.c-flex.c-padding-l-10.c-fotter__list--name
            li.c-padding-l-10.text--b.text__c--white.text--s-slg  = category.name
      - when 3
        = link_to category, class: "u-w-50p c-footer__list" do
          i.fa.fa-female.text--s-lg.text__c--white.c-flex.c-padding-l-10.c-fotter__list--name
            li.c-padding-l-10.text--b.text__c--white.text--s-slg  = category.name
  .c-flex.c-flex__ai-c.c-flex--jc-c
    p.text--s-lg.text--c.c-fotter__title
      = link_to t('site_name'), root_path, class: "u-w-100p text--b text__c--white c-padding-l-10"
    div
      = link_to 'https://twitter.com/girltter_com' do
        i.fa.fa-twitter.text--s-lg.text__c--white.c-flex.c-padding-l-10

app/views/application/s/common/_global_nav_smart_phone.html.slim
nav.p-footer-nav.u-bg-pink.u-w-100p
  ul.c-flex.c-flex__jc-sb.c-margin-reset
    li.c-flex--column.u-w-100p.text--c.text__c--white
      i.fa.fa-home.text--s-xx-lg
      = link_to 'Home', root_path, class: "c-link--c-w"
    li.c-flex--column.u-w-100p.text--c.text__c--white
      i.fa.fa-clock-o.text--s-xx-lg
      = link_to '新着順', root_path, class: "c-link--c-w"
    li.c-flex--column.u-w-100p.text--c.text__c--white
      i.fa.fa-star-o.text--s-xx-lg
      = link_to '人気順', "", class: "c-link--c-w"
    li.c-flex--column.u-w-100p.text--c.text__c--white
      i.fa.fa-search.text--s-xx-lg
      = link_to '見つける', search_topics_path, class: "c-link--c-w"

app/views/application/s/common/_header.html.slim
.u-bg-pink
  .l__header
    header.u-h-100p
      - if params[:controller] == 'top'
        h1.u-font--nunito.text--s-xx-lg.text--c.c-header__title
          = link_to t('site_name'), root_path, class: "c-link--c-w"
      - else
        .u-font--nunito.text--s-xx-lg.text--c.c-header__title
          = link_to t('site_name'), root_path, class: "c-link--c-w"

app/views/application/s/common/_topics_smart_phone.html.slim
- index = local_assigns[:ranking] ? topic_counter + 1 : nil
= link_to topic, class: "c-link__block" do
  li.c-list__item.c-flex.c-border--bottom-1
    - if index.present?
      div class="p-ranking-#{index} text--b"
        span class="p-ranking text__c--white"
          = index
    .c-grid__thumb.c-border__img-r-10
      - if topic.image?
        = image_tag topic.image.url(:thumbnail)
      - elsif topic.thumbnails_first
        = image_tag topic.thumbnails_first
      - else
        = image_tag("no_image.png")
    .c-grid__content.u-w-100p.c-margin-l-10.c-margin-r-10.c-flex--column.c-flex__jc-sb
      .c-grid__title.text--b
        = topic.title
      .c-grid__info.c-flex.c-flex__jc-sb
        div.text__c--pink
          = topic.comments.count
          | コメント
        div.text__c--d-gray
          - if topic.comments.present?
            = topic.comments.last.updated_at.to_s(:Ymd)
          - else
            = topic.updated_at.to_s(:Ymd)