config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  namespace :api, format: 'json' do
    resources :topics, only: %i(create) do
      scope module: :topics do
        resources :comments, only: %i(create)
      end
    end
    resources :categories, only: %i(index)
    resources :icon, only: :index
    post 'reactions/:type/' => 'reactions#create'
    post 'reactions/:type/:reactionable_id' => 'reactions#destroy'
  end

  resources :topics do
    get :reaction_count_map
    collection do
      get :complete
      get :search
    end
    scope module: :topics do
      get 'comments/:no/anchor' => 'comments#anchor', as: 'anchor'
    end
  end
  resources :categories, only: :show, path: 'category'
  get 'tags/:name' => 'tags#index', as: :tags
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_attached_file :image, styles: { medium: '300x300>', thumb: '140x140>' }
  has_many :topics, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates_attachment :image,
                       content_type: { content_type: ['image/jpg',
                                                      'image/jpeg',
                                                      'image/png',
                                                      'image/gif'] }

  scope :ordered_position, -> { order(position: :asc) }
end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category
  before_action :set_tag_ranking

  def show
    @topics = @category.topics.
      order(created_at: :desc).
      page(params[:page])
  end

  private

  def set_category
    @category = Category.find(params[:id])
    @categories = Category.all
  end

  def set_tag_ranking
    @tag_ranking = ActsAsTaggableOn::Tag.most_used
  end
end

app/views/categories/_description.html.slim
.c-container.u-bg-lll-gray.c-border--bottom-1.c-border--top-1
  .l__category__description
    .c-flex
      .p-category__image
        = image_tag(category.image.url(:medium))
      .p-category__description
        h1 = @category.name
        .c-heading--lead = @category.description

app/views/categories/show.html.slim
- content_for :description do
  = render "description", category: @category
- content_for :meta_tags do
  = display_meta_tags(category_meta_tags(@category))
- content_for :tag_ranking do
  = render "application/common/tag_ranking", tags: @tag_ranking
- breadcrumb :category, @category
- content_for :breadcrumbs do
  = render "breadcrumbs"

ul.c-list
  = render partial: "application/common/topics", collection: @topics, as: :topic

app/views/categories/show_smart_phone.html.slim
- content_for :meta_tags do
  = display_meta_tags(category_meta_tags(@category))
- breadcrumb :category, @category
- content_for :breadcrumbs do
  = render "application/s/breadcrumbs"

.text-center.c-padding-l-10.c-padding-r-10
  = link_to "トピックを投稿する", new_topic_path(category_id: params[:id]),
    class: "c-btn c-btn--pink u-w-100p"

ul.c-list
  = render partial: "application/s/common/topics", collection: @topics, as: :topic

= paginate @topics